# This is a basic workflow to help you get started with Actions

name: CI-CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
           
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
         username: ${{secrets.DOCKERHUB_USER}}
         password: ${{secrets.DOCKERHUB_PWD}}
         
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          contect: ./src
          push: true
          tags: |
            felipealves26/kube-news:latest
            felipealves26/kube-news:${{github.run_number}}
                    
        
        
